package server;

public enum RequestType {
	OPEN_THEORETICAL_EXAM, START_THEORETICAL_EXAM, GET_EXAMINATION_CARD, END_THEORETICAL_EXAM, SEND_EXAMINATION_CARD, GET_FREE_TERMS, LOGIN, GET_THEORETICAL_EXAMS, GET_TASKS, ORDER_PRACTICAL, ORDER_THEORETICAL, GET_CATEGORIES, GET_THEORETICAL_EXAMS_FOR_USER, GET_QUESTIONS, GET_EXAMINATION_CARDS, GET_TASK_RESULTS, GET_POSITIONS, ADD_USER, GET_USERS
}	
